// <auto-generated />
using System;
using MChat.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MChat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319132609_CommentUserSeedRemoveWarning")]
    partial class CommentUserSeedRemoveWarning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MChat.Domain.Entities.JwtRefreshTokenUser", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshToken")
                        .HasName("PK_UsersRefreshToken");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersRefreshToken", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<Guid>("Id_Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_Teams");

                    b.HasIndex("Id_Creator");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamRolePermission", b =>
                {
                    b.Property<string>("PermissionName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("perm_name");

                    b.HasKey("PermissionName")
                        .HasName("PK_Teams_Roles_Permissions");

                    b.ToTable("Teams_Roles_Permissions", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(84)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Users__email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UK_Users__username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.JwtRefreshTokenUser", b =>
                {
                    b.HasOne("MChat.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("MChat.Domain.Entities.JwtRefreshTokenUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsersRefreshToken_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamChat", b =>
                {
                    b.HasOne("MChat.Domain.Entities.User", "Creator")
                        .WithMany("MyTeamChats")
                        .HasForeignKey("Id_Creator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Teams_Users");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MChat.Domain.Entities.User", b =>
                {
                    b.Navigation("MyTeamChats");
                });
#pragma warning restore 612, 618
        }
    }
}
