// <auto-generated />
using System;
using MChat.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MChat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307133824_JWTRefreshTokenIntegration")]
    partial class JWTRefreshTokenIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MChat.Domain.Entities.JwtTokenUser", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshToken")
                        .HasName("PK_UsersRefreshToken");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersRefreshToken", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(84)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Users__email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UK_Users__username");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44362eb9-c451-4de3-8509-a3d62711de77"),
                            CreateAt = new DateOnly(2026, 3, 7),
                            LastUpdate = new DateTime(2026, 3, 7, 13, 38, 24, 121, DateTimeKind.Utc).AddTicks(6394),
                            Password = "",
                            Username = "old member"
                        });
                });

            modelBuilder.Entity("MChat.Domain.Entities.JwtTokenUser", b =>
                {
                    b.HasOne("MChat.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("MChat.Domain.Entities.JwtTokenUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsersRefreshToken_Users");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
