// <auto-generated />
using System;
using MChat.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MChat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MChat.Domain.Entities.JwtRefreshTokenUser", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshToken")
                        .HasName("PK_UsersRefreshToken");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersRefreshToken", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_Teams");

                    b.HasIndex("CreatorId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TeamId", "TeamRoleId")
                        .HasName("PK_TeamMembers");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamRoleId");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamRoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_TeamsRoles");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamRoleName", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("UK_TeamsRoles__Team_TeamRole");

                    b.ToTable("TeamsRoles", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamRolePermission", b =>
                {
                    b.Property<string>("PermissionName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("PermissionName")
                        .HasName("PK_TeamsRolesPermissions");

                    b.ToTable("TeamsRolesPermissions", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(84)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Users__email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UK_Users__username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MChat.Infrastructure.JoinEntities.TeamRoleTeamRolePermission", b =>
                {
                    b.Property<string>("PermissionName")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TeamRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionName", "TeamRoleId");

                    b.HasIndex("TeamRoleId");

                    b.ToTable("TeamRoleTeamRolePermission", (string)null);
                });

            modelBuilder.Entity("MChat.Domain.Entities.JwtRefreshTokenUser", b =>
                {
                    b.HasOne("MChat.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("MChat.Domain.Entities.JwtRefreshTokenUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsersRefreshToken_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamChat", b =>
                {
                    b.HasOne("MChat.Domain.Entities.User", "Creator")
                        .WithMany("MyTeamChats")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Teams_Users");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamMember", b =>
                {
                    b.HasOne("MChat.Domain.Entities.TeamChatting.TeamChat", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MChat.Domain.Entities.TeamChatting.TeamRole", "TeamRole")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MChat.Domain.Entities.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("TeamRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamRole", b =>
                {
                    b.HasOne("MChat.Domain.Entities.TeamChatting.TeamChat", "Team")
                        .WithMany("TeamRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TeamsRoles_Teams");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MChat.Infrastructure.JoinEntities.TeamRoleTeamRolePermission", b =>
                {
                    b.HasOne("MChat.Domain.Entities.TeamChatting.TeamRolePermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MChat.Domain.Entities.TeamChatting.TeamRole", null)
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamChat", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("TeamRoles");
                });

            modelBuilder.Entity("MChat.Domain.Entities.TeamChatting.TeamRole", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("MChat.Domain.Entities.User", b =>
                {
                    b.Navigation("MyTeamChats");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
